language: java
env:
  matrix:
    - ISABELLE_VERSION=2016 SCALA_VERSION=2.11.8 PROFILE=quick
    - ISABELLE_VERSION=2016-1-RC0 SCALA_VERSION=2.11.8 PROFILE=quick
  global:
    secure: DCZQfH8QMiLX9nd9ToywysUdD8eEOw6JURZG5JpC8d28XPcZnrdrVZlfGHAp1yCrlldw2anFuLPyz+lmcfirW4vxRpSHlLj4BOybrjPSKTAGfMkQ8tx/8Q2HYilmhK+Le7Qd7vQ61fzOAw7c97pzPT723jA8aAQdqx+LkRPam8w=
install:
  - git submodule update --init --recursive
os:
  - osx
script:
  - ./.ci/travis.sh
deploy:
  - provider: script
    script: ./.ci/deploy.sh
    skip_cleanup: true
    on:
      branch: master
      condition: $DEPLOY = 1
  - provider: bintray
    file: .ci/bintray
    user: larsrh
    skip_cleanup: true
    on:
      branch: master
      condition: $DEPLOY = 1
    key:
      secure: YesgpQ6CanVwyHpp852CEHPOt78hdUSZMvPUDE5x1uAWY4U55qIOAFC9kCEqIkAAvUcq7GSuGGmHzDhlhXQic9nEj/YWkLkTypfE7kUicIqcsjhuwn9OF7n4Tu6zQJv2qMtSl2RlGyNEP2UhtBJHb+ukQA33+p06mBhKHJKZ06I=
matrix:
  include:
    - env: ISABELLE_VERSION=2016 SCALA_VERSION=2.10.6 PROFILE=quick
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - lib32stdc++6
    - env: ISABELLE_VERSION=2016 SCALA_VERSION=2.11.8 PROFILE=slow DEPLOY=1
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - lib32stdc++6
    - env: ISABELLE_VERSION=2016-1-RC0 SCALA_VERSION=2.11.8 PROFILE=slow
      os: linux
      jdk: oraclejdk8
      addons:
        apt:
          packages:
            - lib32stdc++6
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
    - $HOME/.isabelle
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
