install:
  - cinst sbt -y
  - cmd: SET PATH=%PATH%;"C:\Program Files (x86)\sbt\bin"
platform:
  - x86
  - x64
environment:
  matrix:
    - ISABELLE_VERSION: 2016
    - ISABELLE_VERSION: 2016-1
build_script:
  - sbt compile
test_script:
  - sbt "cli/run --version %ISABELLE_VERSION% --internal --session Protocol build"
  - sbt validateQuick
